### ISSUE TITLE
Error Nipe in Kali

### ISSUE THREAD

**Issue by eletricacess** [Aviksaikat/nipe_py#2]
┌──(root㉿kali)-[~]
└─# nipe start
╭───────────────────────────── Traceback (most recent call last) ──────────────────────────────╮
│ /usr/local/lib/python3.11/dist-packages/nipe_py/engine/Start.py:29 in start                  │
│                                                                                              │
│   26 │                                                                                       │
│   27 │   def start(self) -> bool:                                                            │
│   28 │   │   try:                                                                            │
│ ❱ 29 │   │   │   subprocess.check_call(f"tor -f {config_path}/{self.device['distribution']}- │
│   30 │   │   │   subprocess.check_call(self.start_tor, shell=True)                           │
│   31 │   │   │                                                                               │
│   32 │   │   │   for t in self.table:                                                        │
│                                                                                              │
│ /usr/lib/python3.11/subprocess.py:413 in check_call                                          │
│                                                                                              │
│    410 │   │   cmd = kwargs.get("args")                                                      │
│    411 │   │   if cmd is None:                                                               │
│    412 │   │   │   cmd = popenargs[0]                                                        │
│ ❱  413 │   │   raise CalledProcessError(retcode, cmd)                                        │
│    414 │   return 0                                                                          │
│    415                                                                                       │
│    416                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command 'tor -f 
/usr/local/lib/python3.11/dist-packages/nipe_py/engine/../../../.configs/debian-torrc > 
/dev/null' returned non-zero exit status 1.
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
│ [+] nipe has been started....                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by Aviksaikat** [comment]
do you have tor installed ?

**Comment by Aviksaikat** [comment]
I think I have figured out the issue. working on the fix now

**Comment by eletricacess** [comment]
> do you have tor installed ?

Yes

**Comment by Aviksaikat** [comment]
follow the discussion here #3. This is how you should properly document a bug.

**Comment by Aviksaikat** [comment]
The fix has been pushed thanks for your input @eletricacess
